apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashapp
  template:
    metadata:
      labels:
        app: hashapp
    spec:
      containers:
        - name: hashapp
          image: szymonsitko/hash-app:latest