apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 8080
      targetPort: 8080