apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
        - name: crudapp
          image: szymonsitko/crud-app:latest